#!/usr/bin/env zsh

mkdir -p backups

podman run \
  --cidfile cidfile \
  --detach \
  --interactive \
  --publish 25565:25565 \
  --tty \
  --volume $(readlink -f backups):/home/minecraft/backups:U \
  $(cat version/tag)
